---
# - hosts: all
# - import_playbook: ../static-assignments/common-del.yaml


- hosts: uat-webservers
- import_playbook: ../static-assignments/uat-webservers.yaml

---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always